name: Run refresh Everyday

on:
  schedule:
    - cron: '42 21 * * *'

jobs:
  access_refresh_endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Access the endpoint
        run: |
          status_code=$(curl -s -w "%{http_code}" -o response.txt https://lumos-profile.shion.pro/api/refresh)
          
          echo "Response Content:"
          cat response.txt
          
          if [ "$status_code" -ne 200 ]; then
            echo "Error: Unexpected status code $status_code"
            exit 1
          fi
