name: Deploy to GAE
on:
  push:
    branches:
      - "release"
  pull_request:
    paths:
      - ".github/**"
jobs:
  auto_deploy_gae:
    permissions: write-all
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - name: "Generate .env"
        run: |
          echo "${{ secrets.ENV_CONTENTS }}" > .env
      - name: "Extract branch name"
        id: branch-name
        shell: bash
        run: |
          short_ref=${GITHUB_REF#refs/*/}
          formatted_ref=$(echo "$short_ref" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "short_ref=${formatted_ref}" >> $GITHUB_ENV
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: "Deploy to App Engine"
        id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          deliverables: "app.yaml"
          version: ${{ env.short_ref }}
          promote: ${{ env.short_ref =='release' }}
