name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: create .env file
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/938038185918/locations/global/workloadIdentityPools/default/providers/provider-github'
          service_account: 'gh-actions@lumos-profile-management.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Authorize Docker
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: asia-northeast1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/lumos-profile-management/main/nuxt3-release:latest
          context: .
          file: ./cloudrun/Dockerfile

      - name: Download Cloud Run Service YAML
        run: |
          gcloud run services describe release --format yaml --region asia-northeast1 > ./cloudrun-service.yaml

      # replace github_sha field to latest commit sha. Changing spec.template is required to deploy new revision.
      # reference: https://cloud.google.com/run/docs/deploying?hl=ja#revision -- check yaml tab.
      - name: Change some property of service-frontend-release.yaml
        run: |
          sed -i "s/github_sha: .*/github_sha: ${{ github.sha }}/g" ./cloudrun-service.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: "asia-northeast1"
          metadata: "./cloudrun-service.yaml"

      - name: Make CloudRun accessible
        run: |
          gcloud run services add-iam-policy-binding release --region=asia-northeast1 --member=allUsers --role=roles/run.invoker
